# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-18 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='streamName',
            field=models.CharField(max_length=200, verbose_name='streamName'),
        ),
    ]
