# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20180218_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistName', models.CharField(max_length=150, verbose_name='artistName')),
                ('userEmail', models.URLField(verbose_name='userEmail')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
            ],
        ),
    ]
