# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='eventDate',
            field=models.CharField(default='', max_length=150, verbose_name='eventDate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requests',
            name='eventLocation',
            field=models.CharField(default='', max_length=150, verbose_name='eventLocation'),
            preserve_default=False,
        ),
    ]
