# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20180219_0533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='artistName',
            new_name='artist_name',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='eventDate',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='eventLocation',
            new_name='event_location',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='userEmail',
            new_name='user_email',
        ),
    ]
