# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20180220_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streamName', models.CharField(max_length=200, verbose_name='streamName')),
                ('streamArtist', models.CharField(max_length=200, verbose_name='streamArtist')),
                ('streamAuthor', models.CharField(max_length=200, verbose_name='streamAuthor')),
                ('streamDate', models.DateTimeField(verbose_name='streamDate')),
                ('streamDescription', models.TextField(verbose_name='streamDescription')),
                ('streamDislikes', models.IntegerField(verbose_name='streamDislikes')),
                ('streamDuration', models.CharField(max_length=10, verbose_name='streamDuration')),
                ('streamLikes', models.IntegerField(verbose_name='streamLikes')),
                ('streamLocation', models.CharField(max_length=50, verbose_name='streamLocation')),
                ('streamViews', models.IntegerField(verbose_name='streamViews')),
                ('streamURL', models.CharField(max_length=10, verbose_name='streamURL')),
                ('streamFee', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='streamFee')),
                ('streamSetList', models.TextField(verbose_name='streamSetList')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
    ]
